#!/bin/sh
#
# Export release from CVS (tag $1, module $2).
# Create .tar.gz archive
#
# $Id$
#
CVSROOT=:pserver:anonymous@cvs.vtun.sourceforge.net:/cvsroot/vtun
#
if [ $# -ne 2 ]; then
   echo "Usage: create_release CVS_tag CVS_module"
   exit 1
fi 
TAG=$1
MOD=$2
#
REL=`echo $TAG | tr -d 'REL-' | sed 's/\_/\./g'`
DIR=$MOD-$REL
#
cd /tmp
#
echo Exporting CVS tree tag $TAG ...
if ! cvs login; then
  echo CVS login failed
  exit 1
fi 
if ! cvs -z9 export -r $TAG -d $DIR $MOD; then
  echo CVS export failed
  exit 1
fi 

echo "Creating $MOD-$REL ..."

# Create archive
tar czf $MOD-$REL.tar.gz $DIR

# That's it
echo done
