#!/bin/sh
#
#  Universal TUN/TAP device driver.
#  Copyright (C) 1999-2000 Maxim Krasnyansky <max_mk@yahoo.com>
#
#  Create TUN and TAP devices in /dev
#
#  $Id$
#
TUN_MAJOR=90

TUN_MINOR=0
TAP_MINOR=128
#
# TUN
rm -f /dev/tun*
for i in 0 1 2 3 4 5 6 7 8 9 10; do
  mknod /dev/tun$i c ${TUN_MAJOR} $i
done  
#
# TAP
rm -f /dev/tap*
for i in 0 1 2 3 4 5 6 7 8 9 10; do
  mknod /dev/tap$i c ${TUN_MAJOR} `expr $i + ${TAP_MINOR}`
done  
