name: vtun-ng
base: core22
version: '3.0.20'
summary: vtun-ng simple IP-tunneling solution
description: vtun-ng is a simple IP-tunneling solution compatible with vtun

grade: stable
confinement: strict

apps:
  vtunngd:
    command: bin/vtunngd
    plugs:
      - network
      - network-bind
      - network-control
      - system-observe
      - process-control

parts:
  vtun-ng:
    plugin: rust
    source: .
    rust-channel: "1.88.0"
    stage-packages:
      - net-tools
      - iproute2
