name: Build & Release Snap

on:
  push:
    branches: [ snap ]

jobs:
  snap:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Snapcraft
        uses: snapcore/action-build@v1     # sets up LXD + snapcraft

      - name: Upload to Snap Store
        env:
            SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
        run: snapcraft upload vtun-ng_*.snap --release=edge
